apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: orders-file-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.kafka.connect.file.FileStreamSinkConnector
  tasksMax: 1
  config:
    topics: orders
    file: "/tmp/orders-output.txt"
